#!/usr/bin/env bash
# importar-lista-cifrada - agrega las llaves de la lista a nuestro llavero
#
# © 2014 Nicolás Reynolds <fauno@endefensadelsl.org>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
# 
# http://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html
set -e

# debuguear si exportamos la variable DEBUG con cualquier cosa
test ! -z $DEBUG && set -x
# decirle a pinentry qué tty usamos
test -z $GPG_TTY && export GPG_TTY=$(tty)

if test $# -eq 0 ; then
  echo "Importa la llave de una lista en tu llavero y te deja ponerle una contraseña"
  echo
  echo "Uso: ${0##*/} lab@hackcoop.com.ar.asc"
  exit 0
fi

gpg --decrypt <${1} | gpg --import
# TODO asume que es la última subllave importada
gpg --with-colons --list-secret-keys |
grep '@' |
tail -n1 |
cut -d: -f5 | while read subkey; do
  echo "Cambiando la contraseña de ${subkey}"
  gpg --passwd ${subkey}
done

# TODO gpg --passwd con pinentry-curses rompe la terminal :|
# reset
